django_todo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("todo_list.urls"), name="todo_list"),
]

todo_list/urls.py
from django.urls import path

from todo_list.views import (
    TagListView,
    TaskListView,
    TaskUpdateView,
    TaskDeleteView,
    TaskCreateView,
    TagUpdateView,
    TagDeleteView,
    TagCreateView,
    IsDoneUpdateView,
)


urlpatterns = [
    path("", TaskListView.as_view(), name="task-list"),
    path("tasks/create/", TaskCreateView.as_view(), name="task-create"),
    path(
        "tasks/<int:pk>/update/",
        TaskUpdateView.as_view(),
        name="task-update"
    ),
    path(
        "tasks/<int:pk>/delete/",
        TaskDeleteView.as_view(),
        name="task-delete"
    ),
    path(
        "tasks/<int:pk>/change_status/",
        IsDoneUpdateView.as_view(),
        name="change-status"
    ),
    path("tags/", TagListView.as_view(), name="tag-list"),
    path("tags/create/", TagCreateView.as_view(), name="tag-create"),
    path("tags/<int:pk>/update/", TagUpdateView.as_view(), name="tag-update"),
    path("tags/<int:pk>/delete/", TagDeleteView.as_view(), name="tag-delete"),
]


app_name = "todo_list"

todo_list/models.py
from typing import Any

from django.db import models
from django.urls import reverse


class Tag(models.Model):
    name = models.CharField(max_length=63)

    def __str__(self) -> str:
        return self.name

    def get_absolute_url(self) -> Any:
        return reverse("todo_list:tag-list")


class Task(models.Model):
    content = models.TextField()
    datetime = models.DateTimeField(auto_now_add=True)
    deadline = models.DateTimeField(blank=True, null=True)
    is_done = models.BooleanField()
    tags = models.ManyToManyField(to=Tag)

    class Meta:
        ordering = ["is_done", "-datetime"]

    def get_absolute_url(self) -> Any:
        return reverse("todo_list:task-list")

todo_list/views.py
from django.http import HttpRequest
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views import generic, View

from todo_list.models import Tag, Task


class TaskListView(generic.ListView):
    model = Task


class TaskCreateView(generic.CreateView):
    model = Task
    fields = "__all__"
    success_url = reverse_lazy("todo_list:task-list")
    queryset = Task.objects.prefetch_related("tags")


class TaskUpdateView(generic.UpdateView):
    model = Task
    fields = "__all__"
    success_url = reverse_lazy("todo_list:task-list")


class TaskDeleteView(generic.DeleteView):
    model = Task
    success_url = reverse_lazy("todo_list:task-list")


class TagListView(generic.ListView):
    model = Tag


class TagCreateView(generic.CreateView):
    model = Tag
    fields = "__all__"


class TagUpdateView(generic.UpdateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("todo_list:tag-list")


class TagDeleteView(generic.DeleteView):
    model = Tag
    success_url = reverse_lazy("todo_list:tag-list")


# def change_is_done_status(request: HttpRequest, pk: int) -> HttpResponseRedirect:
#     task = Task.objects.get(id=pk)
#     task.is_done = not task.is_done
#     task.save()
#     return HttpResponseRedirect(reverse_lazy("todo_list:task-list"))

class IsDoneUpdateView(View):
    def post(self, request: HttpRequest, pk: int) -> redirect:
        task = Task.objects.get(id=pk)
        task.is_done = not task.is_done
        task.save()
        return redirect("todo_list:task-list")

    def get(self, request: HttpRequest, **kwargs) -> redirect:
        return redirect("todo_list:task-list")

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% block title %}
      <title>To Do</title>
    {% endblock %}
    <meta charset="UTF-8">
    {% load static %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
  </head>

  <body>
    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-2">
          {% block Sidebar %}
            {%  include "includes/sidebar.html" %}
          {% endblock %}
        </div>
        <div class="col-sm-10">
          {% block content %}{% endblock %}
        </div>
      </div>
    </div>
  </body>

</html>

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  <div class="nav-list">
    <li class="list-group-item">
      <a href="{% url 'todo_list:task-list' %}">Home Page</a>
    </li>
    <li class="list-group-item">
      <a href="{% url 'todo_list:tag-list' %}">All tags</a>
    </li>
  </div>
    </ul>

templates/todo_list/tag_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete Tag</h1>

  <p>Are you sure you want to delete the tag {{ tag.name }}?</p>

  <form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Yes, delete" class="btn btn-danger">
  <a class="btn btn-success" href="{% url 'todo_list:tag-list' %}">Cancel</a>
  </form>
{% endblock %}

templates/todo_list/tag_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create"}} Tag </h1>

  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input class="btn btn-primary" type="submit" value="Submit">
  <a class="btn btn-secondary" href="{% url 'todo_list:tag-list' %}">Cancel</a>
  </form>
{% endblock %}

templates/todo_list/tag_list.html
{% extends "base.html" %}

{% block title %}
  <title>To Do | Tags</title>
{% endblock %}

{% block content %}
  <h1>
    Tags
    <a class="create btn btn-success" href="{% url 'todo_list:tag-create' %}">Add new tag</a>
  </h1>
  {% if tag_list %}
    <table class="table">
      <tr>
        <th>Name</th>
        <th>{# Update #}</th>
        <th>{# Delete #}</th>
      </tr>


    {% for tag in tag_list %}
      <tr>
        <td>{{ tag.name }}</td>
        <td><a class="btn btn-secondary" href="{% url 'todo_list:tag-update' pk=tag.id%}">Update</a></td>
        <td><a class="btn btn-danger" href="{% url 'todo_list:tag-delete' pk=tag.id%}">Delete</a></td>
      </tr>
    {% endfor %}
    </table>

    {% else %}
      <p>There is no tag yet.</p>

  {% endif %}
{% endblock %}

templates/todo_list/task_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete Task</h1>

  <p>Are you sure you want to delete the task {{ task.name }}?</p>

  <form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Yes, delete" class="btn btn-danger">
  <a class="btn btn-success" href="{% url 'todo_list:task-list' %}">Cancel</a>
  </form>
{% endblock %}

templates/todo_list/task_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create"}} new Task </h1>

  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input class="btn btn-primary" type="submit" value="Submit">
  <a class="btn btn-secondary" href="{% url 'todo_list:task-list' %}">Cancel</a>
  </form>
{% endblock %}

templates/todo_list/task_list.html
{% extends "base.html" %}

{% block content %}
  
  <h1>
    TODO List
    <a class="btn btn-success create" href="{% url 'todo_list:task-create' %}">Add task</a>
  </h1>
  <br>

  {% if task_list %}
  {% for task in task_list %}
    <h5> {{ task.content }} </h5>

    <form action="{% url 'todo_list:change-status' pk=task.id %}" method="post" novalidate>
      {% csrf_token %}

        {% if task.is_done %}
          <span style="color: forestgreen">Done</span>
          <button class="change-status btn btn-secondary" type="submit">Undo</button>

        {% else %}
          <span style="color: red">Not done</span>
          <button class="change-status btn btn-primary" type="submit">Complete</button>

        {% endif %}
      </form>

    <b>Created at: </b>{{ task.datetime }}<br>

      <b>Tags: </b>
      {% if task.tags.all %}
        {% for tag in task.tags.all %}
          <span>{{ tag }} </span>
        {% endfor %}
        {% else %} <span>No tag added</span>

      {% endif %}
    <br><br>
        <a class="btn btn-secondary" href="{% url 'todo_list:task-update' pk=task.id%}">Update</a>
        <a class="btn btn-danger" href="{% url 'todo_list:task-delete' pk=task.id%}">Delete</a>
      <hr>
    {% endfor %}
    {% else %} There is no task yet.
  {% endif %}
{% endblock %}